weather_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VVYELLG-cr56839
      user: CAIOHANDRADELIMA
      password: Otr@conta1Health
      role: ACCOUNTADMIN
      warehouse: WEATHER_WH
      database: WEATHER_ANALYTICS
      schema: BRONZE
      threads: 4
