retail_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: YS80657.us-east-2.aws
      user: CAIOHANDRADELIMA
      password: Otr@conta1Health
      role: ACCOUNTADMIN
      warehouse: RETAIL_WH
      database: RETAIL_ANALYTICS
      database: BRONZE
      threads: 4
