version: 2

models:
  - name: weather_observations_clean
    description: Cleaned NOAA weather observations
    columns:
      - name: station_id
        tests:
          - not_null

      - name: observation_time_utc
        tests:
          - not_null

      - name: observation_date
        tests:
          - not_null

      - name: temperature_c

      - name: precipitation_last_3h_mm

      - name: is_raining
        tests:
          - not_null
