version: 2

models:
  - name: weather_observations_clean
    description: Cleaned NOAA weather observations with derived rain indicators
    columns:

      - name: station_id
        description: NOAA station identifier
        tests:
          - not_null

      - name: observation_time_utc
        description: Observation timestamp normalized to UTC
        tests:
          - not_null

      - name: observation_date
        description: Observation date (UTC)
        tests:
          - not_null

      - name: temperature_c
        description: Air temperature in Celsius

      - name: is_raining
        description: Derived indicator whether it was raining during the observation
        tests:
          - not_null

      - name: longitude
        tests:
          - not_null

      - name: latitude
        tests:
          - not_null
