version: 2

sources:
  - name: bronze
    database: RETAIL_ANALYTICS
    schema: BRONZE
    tables:
      - name: ORDERS
      - name: PAYMENTS
      - name: SHIPMENTS
      - name: CUSTOMERS
      - name: PRODUCTS
