version: 2

models:
  - name: weather_daily_rain
    description: Daily weather aggregates per station

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - station_id
            - observation_date

    columns:
      - name: station_id
        tests: [not_null]

      - name: observation_date
        tests: [not_null]

      - name: was_raining
        description: Whether it rained at least once during the day
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: total_precip_mm
        description: Total precipitation accumulated during the day
        tests:
          - not_null

      - name: first_observation
        tests: [not_null]

      - name: last_observation
        tests: [not_null]


# weather monthly tests

  - name: weather_monthly_station_rain
    description: Monthly precipitation summary per station

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - station_id
            - month

    columns:
      - name: station_id
        tests: [not_null]

      - name: month
        tests: [not_null]

      - name: monthly_precip_mm
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "value >= 0"

      - name: days_with_data
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "value > 0"

      - name: rainy_days
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "value <= days_with_data"

# weather rainy

  - name: weather_monthly_region_rain
    description: Monthly regional rain summary

    tests:
      - unique:
          column_name: month

    columns:
      - name: month
        tests: [not_null]

      - name: rainy_days_in_month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "value >= 0"

      - name: total_days_observed
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "value > 0"

      - name: rainy_days_in_month
        tests:
          - dbt_utils.expression_is_true:
              expression: "value <= total_days_observed"
