#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./common.sh
source "$SCRIPT_DIR/common.sh"

echo "Create .env"
echo "Run this in Snowflake with ACCOUNTADMIN to validate credentials:"
echo "SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_REGION(), CURRENT_ROLE();"
echo ""

ask() {
  local prompt="$1"
  local default_value="${2:-}"
  local secret="${3:-false}"
  local allow_empty="${4:-false}"
  local value=""
  local prompt_with_default="$prompt"

  if [ -n "$default_value" ]; then
    prompt_with_default="$prompt [$default_value]"
  fi

  if [ "$secret" = "true" ]; then
    read -r -s -p "$prompt_with_default: " value
    echo "" >&2
  else
    read -r -p "$prompt_with_default: " value
  fi

  if [ -z "$value" ]; then
    value="$default_value"
  fi

  if [ -z "$value" ] && [ "$allow_empty" != "true" ]; then
    echo "Value cannot be empty when no default is provided."
    exit 1
  fi

  printf "%s" "$value"
}

# Reuse previous .env values as defaults when available.
if [ -f "$ENV_FILE" ]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
fi

DEFAULT_SNOWFLAKE_ACCOUNT="${SNOWFLAKE_ACCOUNT:-cr56839}"
DEFAULT_SNOWFLAKE_USER="${SNOWFLAKE_USER:-CAIOHANDRADELIMA}"
DEFAULT_SNOWFLAKE_ORG="${SNOWFLAKE_ORGANIZATION_NAME:-VVYELLG}"
DEFAULT_SNOWFLAKE_PASSWORD="${SNOWFLAKE_PASSWORD:-SnowflakePassword123!}"
DEFAULT_SNOWFLAKE_WAREHOUSE="${SNOWFLAKE_WAREHOUSE:-WEATHER_WH}"
DEFAULT_TERRAFORM_WAREHOUSE="${SNOWFLAKE_TERRAFORM_WAREHOUSE:-COMPUTE_WH}"
DEFAULT_SNOWFLAKE_DATABASE="${SNOWFLAKE_DATABASE:-WEATHER_ANALYTICS}"
DEFAULT_SNOWFLAKE_ROLE="${SNOWFLAKE_ROLE:-ACCOUNTADMIN}"
DEFAULT_SNOWFLAKE_SCHEMA="${SNOWFLAKE_SCHEMA:-BRONZE}"

SNOWFLAKE_ACCOUNT="$(ask "Snowflake account (example: YS80657)" "$DEFAULT_SNOWFLAKE_ACCOUNT")"
SNOWFLAKE_USER="$(ask "Snowflake user" "$DEFAULT_SNOWFLAKE_USER")"
SNOWFLAKE_ORGANIZATION_NAME="$(ask "Snowflake organization name" "$DEFAULT_SNOWFLAKE_ORG")"
SNOWFLAKE_PASSWORD="$(ask "Snowflake password" "$DEFAULT_SNOWFLAKE_PASSWORD" true)"
SNOWFLAKE_WAREHOUSE="$(ask "Snowflake warehouse" "$DEFAULT_SNOWFLAKE_WAREHOUSE")"
SNOWFLAKE_TERRAFORM_WAREHOUSE="$(ask "Snowflake Terraform bootstrap warehouse" "$DEFAULT_TERRAFORM_WAREHOUSE")"
SNOWFLAKE_DATABASE="$(ask "Snowflake database" "$DEFAULT_SNOWFLAKE_DATABASE")"
SNOWFLAKE_ROLE="$(ask "Snowflake role" "$DEFAULT_SNOWFLAKE_ROLE")"
SNOWFLAKE_SCHEMA="$(ask "Snowflake schema" "$DEFAULT_SNOWFLAKE_SCHEMA")"

if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
  echo "Existing .env backed up."
fi

cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/setup/create_env.sh
SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT
SNOWFLAKE_ORGANIZATION_NAME=$SNOWFLAKE_ORGANIZATION_NAME
SNOWFLAKE_USER=$SNOWFLAKE_USER
SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
SNOWFLAKE_WAREHOUSE=$SNOWFLAKE_WAREHOUSE
SNOWFLAKE_TERRAFORM_WAREHOUSE=$SNOWFLAKE_TERRAFORM_WAREHOUSE
SNOWFLAKE_DATABASE=$SNOWFLAKE_DATABASE
SNOWFLAKE_ROLE=$SNOWFLAKE_ROLE
SNOWFLAKE_SCHEMA=$SNOWFLAKE_SCHEMA

POSTGRES_USER=airflow
POSTGRES_PASSWORD=airflow
POSTGRES_DB=airflow

AIRBYTE_API_URL=http://host.docker.internal:8000/api/v1
AIRFLOW_FERNET_KEY=not_key
PROJECT_ROOT=$PROJECT_ROOT

WEATHER_PG_HOST=local-postgres
WEATHER_PG_PORT=5433
WEATHER_PG_DB=weather
WEATHER_PG_USER=weather_user
WEATHER_PG_PASSWORD=weather_password

AIRBYTE_CLIENT_ID=
AIRBYTE_CLIENT_SECRET=
POSTGRES_SOURCE_ID=
SNOWFLAKE_DESTINATION_ID=
WORKSPACE_ID=
EOF

echo ".env created at $ENV_FILE"
