USE ROLE ACCOUNTADMIN;

-- Role
CREATE ROLE IF NOT EXISTS TERRAFORM_ROLE;

-- User
CREATE USER IF NOT EXISTS TERRAFORM_USER
  PASSWORD = 'STRONG_P@SSW0RD123'
  DEFAULT_ROLE = TERRAFORM_ROLE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_USER;

-- Inherit SYSADMIN powers
GRANT ROLE SYSADMIN TO ROLE TERRAFORM_ROLE;

GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE DATABASE  ON ACCOUNT TO ROLE TERRAFORM_ROLE;
