version: 2

models:
  - name: products_current
    description: "Latest snapshot of each product"
    columns:
      - name: product_id
        description: "Primary key of the product"
        tests:
          - not_null
          - unique

      - name: product_name
        description: "Name of the product"
        tests:
          - not_null

      - name: price
        description: "Current product price"
        tests:
          - not_null

      - name: active
        description: "Whether the product is active"
        tests:
          - not_null

      - name: last_updated_at
        description: "Date of the latest snapshot"
        tests:
          - not_null
