CREATE ROLE airbyte WITH LOGIN PASSWORD 'airbyte_pass';
GRANT CONNECT ON DATABASE weather TO airbyte;
GRANT USAGE ON SCHEMA observations TO airbyte;
GRANT SELECT ON ALL TABLES IN SCHEMA observations TO airbyte;
ALTER DEFAULT PRIVILEGES IN SCHEMA observations
GRANT SELECT ON TABLES TO airbyte;

ALTER ROLE airbyte WITH REPLICATION;
