CREATE ROLE airbyte WITH LOGIN PASSWORD 'airbyte_pass';
GRANT CONNECT ON DATABASE weather TO airbyte;
GRANT USAGE ON SCHEMA weather TO airbyte;
GRANT SELECT ON ALL TABLES IN SCHEMA weather TO airbyte;
ALTER DEFAULT PRIVILEGES IN SCHEMA weather
GRANT SELECT ON TABLES TO airbyte;

ALTER ROLE airbyte WITH REPLICATION;
