CREATE ROLE airbyte WITH LOGIN PASSWORD 'airbyte_pass';
GRANT CONNECT ON DATABASE retail_prod TO airbyte;
GRANT USAGE ON SCHEMA retail TO airbyte;
GRANT SELECT ON ALL TABLES IN SCHEMA retail TO airbyte;
ALTER DEFAULT PRIVILEGES IN SCHEMA retail
GRANT SELECT ON TABLES TO airbyte;

ALTER ROLE airbyte WITH REPLICATION;
