CREATE ROLE debezium WITH LOGIN PASSWORD 'debezium';
GRANT CONNECT ON DATABASE retail_prod TO debezium;
GRANT USAGE ON SCHEMA retail TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA retail TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA retail
GRANT SELECT ON TABLES TO debezium;

ALTER ROLE debezium REPLICATION;
